const { faker } = require("@faker-js/faker");
const { pickRandom } = require("./helper");

const cities = [
    "Jakarta",
    "Surabaya",
    "Medan",
    "Bandung",
    "Bekasi",
    "Palembang",
    "Tangerang",
    "Makassar",
    "Semarang",
    "Depok",
    "Padang",
    "Bandar Lampung",
    "Bogor",
    "Malang",
    "Pekanbaru",
    "Denpasar",
    "Batam",
    "Bandar Aceh",
    "Banjarmasin",
    "Pontianak",
    "Manado",
    "Balikpapan",
    "Jambi",
    "Ambon",
    "Surakarta",
    "Cirebon",
    "Yogyakarta",
    "Kupang",
    "Palu",
    "Mataram",
    "Madiun",
];
const jobs = [
    "BELUM/TIDAK BEKERJA",
    "MENGURUS RUMAH TANGGA",
    "PELAJAR/MAHASISWA",
    "PENSIUNAN",
    "PEWAGAI NEGERI SIPIL",
    "TENTARA NASIONAL INDONESIA",
    "KEPOLISISAN RI",
    "PERDAGANGAN",
    "PETANI/ PEKEBUN",
    "PETERNAK",
    "NELAYAN/ PERIKANAN",
    "INDUSTRI",
    "KONSTRUKSI",
    "TRANSPORTASI",
    "KARYAWAN SWASTA",
    "KARYAWAN BUMN",
    "KARYAWAN BUMD",
    "KARYAWAN HONORER",
    "BURUH HARIAN LEPAS",
    "BURUH TANI/ PERKEBUNAN",
    "BURUH NELAYAN/ PERIKANAN",
    "BURUH PETERNAKAN",
    "PEMBANTU RUMAH TANGGA",
    "TUKANG CUKUR",
    "TUKANG LISTRIK",
    "TUKANG BATU",
    "TUKANG KAYU",
    "TUKANG SOL SEPATU",
    "TUKANG LAS/ PANDAI BESI",
    "TUKANG JAHIT",
    "TUKANG GIGI",
    "PENATA RIAS",
    "PENATA BUSANA",
    "PENATA RAMBUT",
    "MEKANIK",
    "SENIMAN",
    "TABIB",
    "PARAJI",
    "PERANCANG BUSANA",
    "PENTERJEMAH",
    "IMAM MASJID",
    "PENDETA",
    "PASTOR",
    "WARTAWAN",
    "USTADZ/ MUBALIGH",
    "JURU MASAK",
    "PROMOTOR ACARA",
    "ANGGOTA DPR-RI",
    "ANGGOTA DPD",
    "ANGGOTA BPK",
    "PRESIDEN",
    "WAKIL PRESIDEN",
    "ANGGOTA MAHKAMAH KONSTITUSI",
    "ANGGOTA KABINET/ KEMENTERIAN",
    "DUTA BESAR",
    "GUBERNUR",
    "WAKIL GUBERNUR",
    "BUPATI",
    "WAKIL BUPATI",
    "WALIKOTA",
    "WAKIL WALIKOTA",
    "ANGGOTA DPRD PROVINSI",
    "ANGGOTA DPRD KABUPATEN/ KOTA",
    "DOSEN",
    "GURU",
    "PILOT",
    "PENGACARA",
    "NOTARIS",
    "ARSITEK",
    "AKUNTAN",
    "KONSULTAN",
    "DOKTER",
    "BIDAN",
    "PERAWAT",
    "APOTEKER",
    "PSIKIATER/ PSIKOLOG",
    "PENYIAR TELEVISI",
    "PENYIAR RADIO",
    "PELAUT",
    "PENELITI",
    "SOPIR",
    "PIALANG",
    "PARANORMAL",
    "PEDAGANG",
    "PERANGKAT DESA",
    "KEPALA DESA",
    "BIARAWATI",
    "WIRASWASTA",
];
function imageUpload() {
    return {
        status: 200,
        data: {
            image: {
                id: faker.number.int(),
                user_name: "no_name",
                created_at: new Date(),
                updated_at: new Date(),
                image: "/images/",
            },
        },
    };
}

function generateKtpData() {
    return {
        status: 200,
        data: {
            result: {
                nik: faker.string.numeric(15),
                nama: faker.person.fullName(),
                tempat_lahir: pickRandom(cities),
                tanggal_lahir: faker.date.birthdate(),
                jenis_kelamin: pickRandom(["LAKI-LAKI", "PEREMPUAN"]),
                golongan_darah: pickRandom("A", "B", "AB", "O"),
                rt: faker.number.int({ min: 1, max: 20 }),
                rw: faker.number.int({ min: 1, max: 20 }),
                alamat: faker.location.streetAddress(),
                kelurahan_atau_desa: faker.location.city(),
                kecamatan: faker.location.state(),
                agama: pickRandom([
                    "ISLAM",
                    "KRISTEN",
                    "KATHOLIK",
                    "BUDHA",
                    "HINDU",
                    "KONGHUCU",
                ]),
                status_perkawinan: pickRandom(["KAWIN", "BELUM KAWIN"]),
                pekerjaan: pickRandom(jobs),
                kewarganegaraan: pickRandom(["WNI", "WNA"]),
                berlaku_hingga: "SEUMUR HIDUP",
                SCORE_OCR: faker.number.float({ precision: 2, min: 1 }),
                SCORE_ASID: Math.round(Math.random() * 100) / 100,
                SCORE_CAT: pickRandom([
                    "Verifikasi Sangat Baik & Fraud Sangat Rendah",
                    "Verifikasi Baik & Fraud Rendah",
                    "Verifikasi Buruk & Fraud Tinggi",
                    "Verifikasi Sangat Buruk & Fraud Sangat Tinggi",
                ]),
                PREDICATE: pickRandom(["Aa+", "Bb+", "Cc-", "Dd-"]),
            },
        },
    };
}

function generateSiup() {
    return {
        company_name: faker.company.name(),
        bussiness_registration_number: faker.string.numeric(13),
        company_address: faker.location.streetAddress(),
        kbli_name: faker.lorem.words(4),
        kbli_code: faker.number.int({ max: 99999 }),
        address: faker.location.streetAddress(),
        sub_district: faker.location.city(),
        district: faker.location.city(),
        regency: faker.location.state(),
        province: faker.location.state(),
        issued_date: faker.date.past(),
    };
}

function generateNpwp() {
    return {
        code_npwp: faker.string.numeric(12),
        company_name: faker.company.name(),
        company_address: faker.location.streetAddress(),
        registered: faker.date.past(),
    };
}

function generateSkdp() {
    return {
        skdp_number: faker.string.numeric(10),
        name: faker.person.fullName(),
        place_of_birth: faker.location.city(),
        date_of_birth: faker.date.birthdate(),
        gender: faker.person.sex(),
        religion: pickRandom(["islam", "kristen", "katholik", "hindu", "budha"]),
        citizenship: faker.location.country(),
        id_card_number: faker.string.numeric(20),
        occupation: faker.person.jobType(),
        company_name: faker.company.name(),
        bussiness_category: faker.commerce.department(),
        business_address: faker.location.streetAddress(),
        contact_number: faker.phone.number(),
        building_status: pickRandom(["milik sendiri", "sewa"]),
        establishment_deed_number: faker.date.past(),
        staff_number: faker.number.int(),
        person_in_charge: faker.person.fullName(),
    };
}

function generateTdp() {
    return {
        tdp_number: faker.string.numeric(20),
        npwp_number: faker.string.numeric(20),
        kbli: faker.number.int(),
    };
}

function generateCompleteDocument() {
    return {
        ktp: generateKtpData(),
        surat_izin_usaha_perdagangan: generateSiup(),
        surat_keterangan_domisili_usaha: generateSkdp(),
        npwp: generateNpwp(),
        surat_tanda_daftar_perusahaan: generateTdp(),
    };
}

module.exports = {
    generateKtpData,
    generateNpwp,
    generateSiup,
    generateSkdp,
    generateTdp,
    generateCompleteDocument,
    imageUpload,
};
